/**
 * 《时空语航员》课程素材库
 * 教材：沪教牛津深圳版小学英语（经典版，对齐 GDD 中 Kitty / Peter / Alice / Miss Fang 等 NPC）
 * 内容来源：公开教材单词表 / 知识点清单（网络搜索整理）
 *
 * 数据结构：
 *   COURSE_DATA = [ grade ]
 *   grade = { id, name, modules:[ unit ] }
 *   unit = {
 *     id, name, theme,                       // 关卡基本信息
 *     vocab:    [ { en, zh } ],              // 词汇（基础弹药库）
 *     dialogue: [ { speaker, prompt, zh, answer } ] // 课文会话（进阶激光炮）
 *   }
 */

const COURSE_DATA = [
  {
    id: "3A",
    name: "三年级上册 (3A)",
    units: [
      {
        id: "3A-U1",
        name: "Unit 1 Hello",
        theme: "问候星域",
        npc: "Peter",
        vocab: [
          { en: "hello", zh: "你好" },
          { en: "hi", zh: "你好（打招呼）" },
          { en: "I", zh: "我" },
          { en: "my", zh: "我的" },
          { en: "she", zh: "她" },
          { en: "is", zh: "是" },
          { en: "Miss", zh: "小姐" },
          { en: "Kitty", zh: "凯蒂" },
          { en: "Peter", zh: "彼得" },
          { en: "Alice", zh: "艾丽丝" },
          { en: "Joe", zh: "乔" },
        ],
        dialogue: [
          { speaker: "Peter", prompt: "Hello, I'm Peter.", zh: "你好，我是彼得。", answer: "Hello, Peter." },
          { speaker: "Miss Fang", prompt: "Good morning, class.", zh: "同学们早上好。", answer: "Good morning, Miss Fang." },
          { speaker: "Kitty", prompt: "Hi, I'm Kitty.", zh: "嗨，我是凯蒂。", answer: "Hi, Kitty." },
        ],
      },
      {
        id: "3A-U2",
        name: "Unit 2 Good morning",
        theme: "晨曦星域",
        npc: "Miss Fang",
        vocab: [
          { en: "are", zh: "是" },
          { en: "fine", zh: "身体好的" },
          { en: "goodbye", zh: "再见" },
          { en: "Mr", zh: "先生" },
          { en: "Mrs", zh: "太太" },
          { en: "thank", zh: "谢谢" },
          { en: "you", zh: "你；你们" },
          { en: "morning", zh: "早晨" },
          { en: "afternoon", zh: "下午" },
        ],
        dialogue: [
          { speaker: "Mr Li", prompt: "How are you?", zh: "你好吗？", answer: "I'm fine. Thank you." },
          { speaker: "Alice", prompt: "Goodbye, Peter.", zh: "再见，彼得。", answer: "Goodbye, Alice." },
          { speaker: "Mrs Wang", prompt: "Good afternoon.", zh: "下午好。", answer: "Good afternoon." },
        ],
      },
      {
        id: "3A-U3",
        name: "Unit 3 Yes or no",
        theme: "抉择星域",
        npc: "Kitty",
        vocab: [
          { en: "am", zh: "是" },
          { en: "girl", zh: "女孩" },
          { en: "boy", zh: "男孩" },
          { en: "yes", zh: "是；对" },
          { en: "no", zh: "不；不是" },
          { en: "not", zh: "不是" },
        ],
        dialogue: [
          { speaker: "Joe", prompt: "Are you Kitty?", zh: "你是凯蒂吗？", answer: "Yes, I am." },
          { speaker: "Alice", prompt: "Are you a boy?", zh: "你是男孩吗？", answer: "No, I'm not." },
        ],
      },
      {
        id: "3A-U4",
        name: "Unit 4 My friends",
        theme: "挚友星域",
        npc: "Ben",
        vocab: [
          { en: "fat", zh: "胖的" },
          { en: "thin", zh: "瘦的" },
          { en: "tall", zh: "高的" },
          { en: "short", zh: "矮的" },
          { en: "friend", zh: "朋友" },
          { en: "he", zh: "他" },
          { en: "this", zh: "这；这个" },
        ],
        dialogue: [
          { speaker: "Kitty", prompt: "This is my friend.", zh: "这是我的朋友。", answer: "He is tall." },
          { speaker: "Peter", prompt: "Is she thin?", zh: "她瘦吗？", answer: "Yes, she is thin." },
        ],
      },
      {
        id: "3A-U5",
        name: "Unit 5 My family",
        theme: "家园星域",
        npc: "Alice",
        vocab: [
          { en: "father", zh: "父亲；爸爸" },
          { en: "mother", zh: "母亲；妈妈" },
          { en: "brother", zh: "哥哥；弟弟" },
          { en: "sister", zh: "姐姐；妹妹" },
          { en: "me", zh: "我" },
          { en: "who", zh: "谁" },
          { en: "beautiful", zh: "漂亮的" },
        ],
        dialogue: [
          { speaker: "Kitty", prompt: "Who is she?", zh: "她是谁？", answer: "She is my mother." },
          { speaker: "Ben", prompt: "Who is he?", zh: "他是谁？", answer: "He is my father." },
        ],
      },
      {
        id: "3A-U6",
        name: "Unit 6 My face",
        theme: "容颜星域",
        npc: "Ben",
        vocab: [
          { en: "eye", zh: "眼睛" },
          { en: "ear", zh: "耳朵" },
          { en: "face", zh: "脸；面孔" },
          { en: "mouth", zh: "口；嘴巴" },
          { en: "hair", zh: "头发" },
          { en: "nose", zh: "鼻子" },
          { en: "big", zh: "大的" },
          { en: "small", zh: "小的" },
          { en: "long", zh: "长的" },
          { en: "look", zh: "看" },
        ],
        dialogue: [
          { speaker: "Alice", prompt: "Look at my face.", zh: "看我的脸。", answer: "Your eyes are big." },
          { speaker: "Kitty", prompt: "Her hair is long.", zh: "她的头发很长。", answer: "Yes, it is long." },
        ],
      },
      {
        id: "3A-U7",
        name: "Unit 7 In the classroom",
        theme: "课堂星域",
        npc: "Miss Fang",
        vocab: [
          { en: "blackboard", zh: "黑板" },
          { en: "door", zh: "门" },
          { en: "window", zh: "窗户" },
          { en: "clean", zh: "打扫干净" },
          { en: "close", zh: "关上" },
          { en: "open", zh: "打开" },
          { en: "late", zh: "迟到" },
          { en: "please", zh: "请" },
          { en: "look at", zh: "看……" },
        ],
        dialogue: [
          { speaker: "Miss Fang", prompt: "Open the door, please.", zh: "请打开门。", answer: "OK." },
          { speaker: "Miss Fang", prompt: "Clean the blackboard, please.", zh: "请把黑板擦干净。", answer: "Very good!" },
        ],
      },
      {
        id: "3A-U8",
        name: "Unit 8 At the shop",
        theme: "市集星域",
        npc: "Joe",
        vocab: [
          { en: "apple", zh: "苹果" },
          { en: "banana", zh: "香蕉" },
          { en: "orange", zh: "橙子" },
          { en: "dad", zh: "爸爸" },
          { en: "good", zh: "好的" },
          { en: "here", zh: "这里" },
          { en: "it", zh: "它" },
          { en: "they", zh: "它们；他们" },
          { en: "how much", zh: "多少钱" },
        ],
        dialogue: [
          { speaker: "Shopkeeper", prompt: "How much is it?", zh: "它多少钱？", answer: "Here you are." },
          { speaker: "Dad", prompt: "Good afternoon.", zh: "下午好。", answer: "Good afternoon." },
        ],
      },
      {
        id: "3A-U9",
        name: "Unit 9 The four seasons",
        theme: "四季星域",
        npc: "Kitty",
        vocab: [
          { en: "spring", zh: "春天" },
          { en: "summer", zh: "夏天" },
          { en: "autumn", zh: "秋天" },
          { en: "winter", zh: "冬天" },
          { en: "warm", zh: "温暖的" },
          { en: "hot", zh: "炎热的" },
          { en: "cool", zh: "凉爽的" },
          { en: "cold", zh: "寒冷的" },
        ],
        dialogue: [
          { speaker: "Alice", prompt: "It's hot in summer.", zh: "夏天很热。", answer: "Yes, it's hot." },
          { speaker: "Ben", prompt: "It's cold in winter.", zh: "冬天很冷。", answer: "Yes, it's cold." },
        ],
      },
      {
        id: "3A-U10",
        name: "Unit 10 Numbers",
        theme: "数字星域",
        npc: "Peter",
        vocab: [
          { en: "one", zh: "一" },
          { en: "two", zh: "二" },
          { en: "three", zh: "三" },
          { en: "four", zh: "四" },
          { en: "five", zh: "五" },
          { en: "six", zh: "六" },
          { en: "seven", zh: "七" },
          { en: "eight", zh: "八" },
          { en: "nine", zh: "九" },
          { en: "ten", zh: "十" },
        ],
        dialogue: [
          { speaker: "Kitty", prompt: "How many apples?", zh: "有多少个苹果？", answer: "Three apples." },
          { speaker: "Joe", prompt: "Count to ten.", zh: "数到十。", answer: "Eight, nine, ten." },
        ],
      },
      {
        id: "3A-U11",
        name: "Unit 11 Small animals",
        theme: "萌宠星域",
        npc: "Alice",
        vocab: [
          { en: "cat", zh: "猫" },
          { en: "dog", zh: "狗" },
          { en: "fish", zh: "鱼" },
          { en: "mouse", zh: "老鼠" },
          { en: "rabbit", zh: "兔子" },
          { en: "tail", zh: "尾巴" },
          { en: "its", zh: "它的" },
          { en: "what", zh: "什么" },
        ],
        dialogue: [
          { speaker: "Ben", prompt: "What is it?", zh: "它是什么？", answer: "It is a rabbit." },
          { speaker: "Kitty", prompt: "Its tail is short.", zh: "它的尾巴很短。", answer: "Well done!" },
        ],
      },
      {
        id: "3A-U12",
        name: "Unit 12 Things I like",
        theme: "心仪星域",
        npc: "Kitty",
        vocab: [
          { en: "pen", zh: "钢笔" },
          { en: "pencil", zh: "铅笔" },
          { en: "ruler", zh: "尺子" },
          { en: "book", zh: "书" },
          { en: "schoolbag", zh: "书包" },
          { en: "desk", zh: "书桌" },
          { en: "chair", zh: "椅子" },
          { en: "bed", zh: "床" },
          { en: "these", zh: "这些" },
          { en: "your", zh: "你的" },
        ],
        dialogue: [
          { speaker: "Alice", prompt: "Is this your pen?", zh: "这是你的钢笔吗？", answer: "Yes, it is." },
          { speaker: "Peter", prompt: "These are my books.", zh: "这些是我的书。", answer: "Welcome!" },
        ],
      },
    ],
  },
  {
    id: "3B",
    name: "三年级下册 (3B)",
    units: [
      {
        id: "3B-U1",
        name: "Unit 1 Colours",
        theme: "彩虹星域",
        npc: "Kitty",
        vocab: [
          { en: "red", zh: "红色的" },
          { en: "blue", zh: "蓝色的" },
          { en: "green", zh: "绿色的" },
          { en: "yellow", zh: "黄色的" },
          { en: "black", zh: "黑色的" },
          { en: "white", zh: "白色的" },
          { en: "orange", zh: "橙色的" },
          { en: "colour", zh: "颜色" },
        ],
        dialogue: [
          { speaker: "Alice", prompt: "What colour is your ball?", zh: "你的球是什么颜色的？", answer: "It's red." },
          { speaker: "Ben", prompt: "What colour is the panda?", zh: "熊猫是什么颜色的？", answer: "It's black and white." },
        ],
      },
      {
        id: "3B-U2",
        name: "Unit 2 Taste and feel",
        theme: "五感星域",
        npc: "Peter",
        vocab: [
          { en: "sweet", zh: "甜的" },
          { en: "sour", zh: "酸的" },
          { en: "hard", zh: "硬的" },
          { en: "soft", zh: "软的" },
          { en: "candy", zh: "糖果" },
          { en: "lemon", zh: "柠檬" },
          { en: "ice cream", zh: "冰淇淋" },
          { en: "taste", zh: "味道；尝" },
        ],
        dialogue: [
          { speaker: "Kitty", prompt: "How does it feel?", zh: "它摸起来怎么样？", answer: "It's soft." },
          { speaker: "Alice", prompt: "How does the lemon taste?", zh: "柠檬尝起来怎么样？", answer: "It's sour." },
        ],
      },
      {
        id: "3B-U3",
        name: "Unit 3 Transport",
        theme: "驰骋星域",
        npc: "Joe",
        vocab: [
          { en: "bike", zh: "自行车" },
          { en: "bus", zh: "公共汽车" },
          { en: "car", zh: "小汽车" },
          { en: "train", zh: "火车" },
          { en: "plane", zh: "飞机" },
          { en: "ship", zh: "船" },
          { en: "can", zh: "能；会" },
          { en: "hear", zh: "听见" },
        ],
        dialogue: [
          { speaker: "Ben", prompt: "What is it?", zh: "它是什么？", answer: "It's a plane." },
          { speaker: "Peter", prompt: "Can you hear the train?", zh: "你能听见火车吗？", answer: "Yes, I can." },
        ],
      },
    ],
  },
  {
    id: "4A",
    name: "四年级上册 (4A)",
    units: [
      {
        id: "4A-U1",
        name: "Unit 1 Meeting new people",
        theme: "邂逅星域",
        npc: "Kitty",
        vocab: [
          { en: "meet", zh: "相识；遇见" },
          { en: "name", zh: "名字" },
          { en: "classmate", zh: "同班同学" },
          { en: "morning", zh: "早晨；上午" },
          { en: "afternoon", zh: "下午" },
          { en: "his", zh: "他的" },
          { en: "her", zh: "她的" },
          { en: "new", zh: "新的" },
        ],
        dialogue: [
          { speaker: "Peter", prompt: "Nice to meet you.", zh: "很高兴认识你。", answer: "Nice to meet you, too." },
          { speaker: "Miss Fang", prompt: "What's her name?", zh: "她叫什么名字？", answer: "Her name is Alice." },
        ],
      },
      {
        id: "4A-U2",
        name: "Unit 2 Can you swim?",
        theme: "技能星域",
        npc: "Ben",
        vocab: [
          { en: "run", zh: "跑" },
          { en: "fly", zh: "飞；放飞" },
          { en: "draw", zh: "画画" },
          { en: "write", zh: "写字" },
          { en: "jump", zh: "跳" },
          { en: "swim", zh: "游泳" },
          { en: "fast", zh: "快地；快的" },
          { en: "sit", zh: "坐" },
        ],
        dialogue: [
          { speaker: "Kitty", prompt: "Can you swim?", zh: "你会游泳吗？", answer: "Yes, I can." },
          { speaker: "Peter", prompt: "Can you fly?", zh: "你会飞吗？", answer: "No, I can't." },
        ],
      },
      {
        id: "4A-U3",
        name: "Unit 3 Are you happy?",
        theme: "情绪星域",
        npc: "Alice",
        vocab: [
          { en: "happy", zh: "开心的" },
          { en: "sad", zh: "难过的" },
          { en: "tired", zh: "累的" },
          { en: "hungry", zh: "饥饿的" },
          { en: "thirsty", zh: "口渴的" },
          { en: "full", zh: "饱的" },
          { en: "drink", zh: "喝" },
          { en: "see", zh: "看见" },
        ],
        dialogue: [
          { speaker: "Ben", prompt: "Are you happy?", zh: "你开心吗？", answer: "Yes, I am happy." },
          { speaker: "Kitty", prompt: "Are you hungry?", zh: "你饿吗？", answer: "Yes, I'm hungry." },
        ],
      },
    ],
  },
  {
    id: "5A",
    name: "五年级上册 (5A)",
    units: [
      {
        id: "5A-U1",
        name: "Unit 1 My future",
        theme: "未来星域",
        npc: "Peter",
        vocab: [
          { en: "want", zh: "想要" },
          { en: "future", zh: "未来" },
          { en: "cook", zh: "厨师；烹饪" },
          { en: "doctor", zh: "医生" },
          { en: "teacher", zh: "老师" },
          { en: "pilot", zh: "飞行员" },
          { en: "be good at", zh: "擅长" },
          { en: "afraid", zh: "害怕的" },
        ],
        dialogue: [
          { speaker: "Kitty", prompt: "What do you want to be?", zh: "你想成为什么？", answer: "I want to be a pilot." },
          { speaker: "Ben", prompt: "Are you good at maths?", zh: "你擅长数学吗？", answer: "Yes, I am." },
        ],
      },
      {
        id: "5A-U2",
        name: "Unit 2 Going to school",
        theme: "求学星域",
        npc: "Alice",
        vocab: [
          { en: "come", zh: "来" },
          { en: "school", zh: "学校" },
          { en: "by bus", zh: "乘公共汽车" },
          { en: "on foot", zh: "步行" },
          { en: "subway", zh: "地铁" },
          { en: "cross", zh: "穿过" },
          { en: "straight", zh: "笔直地" },
          { en: "right", zh: "右边的" },
        ],
        dialogue: [
          { speaker: "Peter", prompt: "How do you come to school?", zh: "你怎么来学校？", answer: "I come by bus." },
          { speaker: "Kitty", prompt: "Turn right, please.", zh: "请右转。", answer: "OK, turn right." },
        ],
      },
      {
        id: "5A-U3",
        name: "Unit 3 My birthday",
        theme: "庆典星域",
        npc: "Kitty",
        vocab: [
          { en: "first", zh: "第一" },
          { en: "second", zh: "第二" },
          { en: "third", zh: "第三" },
          { en: "party", zh: "派对；聚会" },
          { en: "bring", zh: "带来" },
          { en: "wear", zh: "穿着" },
          { en: "favourite", zh: "最喜欢的" },
          { en: "present", zh: "礼物" },
        ],
        dialogue: [
          { speaker: "Alice", prompt: "When is your birthday?", zh: "你的生日是什么时候？", answer: "It is on the 19th of September." },
          { speaker: "Ben", prompt: "Welcome to my party.", zh: "欢迎来我的派对。", answer: "Happy Birthday!" },
        ],
      },
    ],
  },
];

if (typeof window !== "undefined") {
  window.COURSE_DATA = COURSE_DATA;
}
